### ISSUE TITLE
Fatal error: Class 'Mongo_Database' not found

### ISSUE THREAD

**Issue by sumit450** [colinmollenhour/magento-mongo#20]
Dear colin,
I have a following error  when I include your module in Magento, Please help me out to resolve this error.
Fatal error: Class 'Mongo_Database' not found in /var/www/magento/app/code/community/Cm/Mongo/Model/Resource/Type/Shim.php on line 3
Thanks

**Comment by colinmollenhour** [comment]
This repo uses git submodules so you are probably missing the submodule.

**Comment by price2b** [comment]
just a comment for people installing manually. This file Modman contains routes that must be maintained.

mainly:

# Map file names to be autoload friendly
lib/mongodb-php-odm/classes/json.php                      lib/JSON.php
lib/mongodb-php-odm/classes/mongo/database.php            lib/Mongo/Database.php
lib/mongodb-php-odm/classes/mongo/collection.php          lib/Mongo/Collection.php

consequently you must take json.php and place that file with UPPERCASE in Lib/
You must take mongodb-php-odm/classes/mongo and put it in Lib/Mongo(create the folder with mongo in Capitalize)/Collection.php (in capitalize too).
same operation for Database.php.

hope it helps.
