### ISSUE TITLE
do we have to define a schema of our mongodb?

### ISSUE THREAD

**Issue by price2b** [colinmollenhour/magento-mongo#23]
I read the code of mongo.xml.sample. Do we have to manually define the schema of our mongodb?

im confused with this information, brgds!:

      
      <foo>
        
        <bar>
      <collection>foobar</collection>   
      <autoincrement/>                  
      <created_timestamp/>              
      <updated_timestamp/>              
      <fields>
        <_id>          <type>int</type></_id>
        <baz_id>       <type>reference</type><model>foo/baz</model></baz_id>
        <address>      <type>embedded</type><model>foo/address</model></address>
        <email/>       
        <password>     <type>mongo/type_encrypted</type></password>
        <status>       <type>enum</type>
                         <options>
                           <inactive/>
                           <pending/>
                           <active/>
                           <suspended/>
                         </options>
                       </status>
        <active>       <type>bool</type></active>
        <roles>        <type>set</type><subtype>string</subtype></roles>
        <created_at>   <type>MongoDate</type></created_at>
        <updated_at>   <type>MongoDate</type></updated_at>
      </fields>

**Comment by colinmollenhour** [comment]
Yes, as it is a sort of "ORM" it needs a schema for all of the casting magic and other features. If you don't want a schema then I suggest you just use the Mongo driver or the Mongo_Document and Mongo_Collection classes directly as it is already OO. You could do that using something like Mage::getSingleton('core/resource')->getConnection('mongo_write')->...

**Comment by price2b** [comment]
Great. Thank you so much for your answer.

El Tuesday, January 5, 2016, Colin Mollenhour <notifications@github.com>
escribió:

> Yes, as it is a sort of "ORM" it needs a schema for all of the casting
> magic and other features. If you don't want a schema then I suggest you
> just use the Mongo driver or the Mongo_Document and Mongo_Collection
> classes directly as it is already OO. You could do that using something
> like Mage::getSingleton('core/resource')->getConnection('mongo_write')->...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/colinmollenhour/magento-mongo/issues/23#issuecomment-168927252>
> .
>


-- 

Sebastian Herrera
Director | price2b.com | US: (302) 476-2774 | HK:(852) 8191-2774 |
siherrera@price2b.com | www.price2b.com

© 2015 price2b.com, inc. All rights reserved. Various trademarks held by
their respective owners.

Privacy Statement: http://www.price2b.com/company/terms

Price2b, Inc. 501 Silverside Road, Suite 105, Wilmington, DE 19809 United
States
