### ISSUE TITLE
Update to php7 display the following error. (mongo not found)

### ISSUE THREAD

**Issue by price2b** [colinmollenhour/magento-mongo#24]
Dear Colin,

if CM_Mongo.xml is set `<active>true</active>` the following error is displayed in frontend

> ( ! ) Fatal error: Uncaught Error: Class 'Mongo' not found in C:\Program Files (x86)\Zend\Apache24\htdocs\lib\Mongo\Database.php on line 182
> ( ! ) Error: Class 'Mongo' not found in C:\Program Files (x86)\Zend\Apache24\htdocs\lib\Mongo\Database.php on line 182

I supposed is related to my server php7 update, do you know if any problem could appear using that version?.

Im using magento 1.9.2 with extension https://github.com/Inchoo/Inchoo_PHP7 for php7 + php_mongo.dll for phpv7. if i set `<active>false</active>` the app works ok.

any guideline appreciated. brgds

**Comment by colinmollenhour** [comment]
https://docs.mongodb.org/ecosystem/drivers/php/
